// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"codewiki/internal/biz"
	"codewiki/internal/conf"
	"codewiki/internal/data"
	"codewiki/internal/data/repo"
	"codewiki/internal/server"
	"codewiki/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	driverWithContext := data.NewDriverWithContext(dataData)
	entityRepo := repo.NewEntityRepo(driverWithContext)
	codeWiki := biz.NewCodeWiki(entityRepo)
	codeWikiService := service.NewCodeWikiService(codeWiki)
	httpServer := server.NewHTTPServer(confServer, codeWikiService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
