// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"codewiki/internal/biz"
	"codewiki/internal/conf"
	"codewiki/internal/data"
	"codewiki/internal/data/repo"
	"codewiki/internal/pkg/llm"
	"codewiki/internal/server"
	"codewiki/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	driverWithContext := data.NewDriverWithContext(dataData)
	codeRepo := repo.NewCodeNeo4jRepo(driverWithContext)
	db, err := data.NewGormDB(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repositoryRepo := repo.NewRepositoryRepo(db)
	entityRepo := repo.NewEntityRepo(driverWithContext)
	config := biz.NewConfig(confData)
	llmLLM := llm.NewLLM(config)
	indexerRepo := repo.NewIndexerRepo(confData)
	indexer := biz.NewIndexer(llmLLM, indexerRepo)
	codeAnalyzer := biz.NewCodeAnalyzer(codeRepo, repositoryRepo, entityRepo, indexer, confData)
	codeAnalyzerService := service.NewCodeAnalyzerService(codeAnalyzer)
	qaEngine := biz.NewQAEngine(llmLLM, indexer, codeRepo, repositoryRepo)
	qaService := service.NewQAService(qaEngine)
	repositoryBiz := biz.NewRepositoryBiz(indexer, codeRepo, entityRepo, repositoryRepo)
	repositoryService := service.NewRepositoryService(repositoryBiz)
	httpServer := server.NewHTTPServer(confServer, codeAnalyzerService, qaService, repositoryService, logger)
	mcpService := service.NewMCPService(codeAnalyzerService, repositoryService, qaService)
	mcpServer := server.NewMCPServer(confServer, mcpService)
	app := newApp(logger, httpServer, mcpServer)
	return app, func() {
		cleanup()
	}, nil
}
