// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: codewiki/v1/codewiki.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeWikiService_Analyze_FullMethodName = "/codewiki.v1.CodeWikiService/Analyze"
)

// CodeWikiServiceClient is the client API for CodeWikiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeWikiServiceClient interface {
	Analyze(ctx context.Context, in *AnalyzeReq, opts ...grpc.CallOption) (*AnalyzeResp, error)
}

type codeWikiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeWikiServiceClient(cc grpc.ClientConnInterface) CodeWikiServiceClient {
	return &codeWikiServiceClient{cc}
}

func (c *codeWikiServiceClient) Analyze(ctx context.Context, in *AnalyzeReq, opts ...grpc.CallOption) (*AnalyzeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResp)
	err := c.cc.Invoke(ctx, CodeWikiService_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeWikiServiceServer is the server API for CodeWikiService service.
// All implementations must embed UnimplementedCodeWikiServiceServer
// for forward compatibility.
type CodeWikiServiceServer interface {
	Analyze(context.Context, *AnalyzeReq) (*AnalyzeResp, error)
	mustEmbedUnimplementedCodeWikiServiceServer()
}

// UnimplementedCodeWikiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeWikiServiceServer struct{}

func (UnimplementedCodeWikiServiceServer) Analyze(context.Context, *AnalyzeReq) (*AnalyzeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedCodeWikiServiceServer) mustEmbedUnimplementedCodeWikiServiceServer() {}
func (UnimplementedCodeWikiServiceServer) testEmbeddedByValue()                         {}

// UnsafeCodeWikiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeWikiServiceServer will
// result in compilation errors.
type UnsafeCodeWikiServiceServer interface {
	mustEmbedUnimplementedCodeWikiServiceServer()
}

func RegisterCodeWikiServiceServer(s grpc.ServiceRegistrar, srv CodeWikiServiceServer) {
	// If the following call pancis, it indicates UnimplementedCodeWikiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeWikiService_ServiceDesc, srv)
}

func _CodeWikiService_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeWikiServiceServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeWikiService_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeWikiServiceServer).Analyze(ctx, req.(*AnalyzeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeWikiService_ServiceDesc is the grpc.ServiceDesc for CodeWikiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeWikiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codewiki.v1.CodeWikiService",
	HandlerType: (*CodeWikiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _CodeWikiService_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "codewiki/v1/codewiki.proto",
}
