// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: codewiki/v1/codewiki.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRepoServiceAnalyzeRepo = "/codewiki.v1.RepoService/AnalyzeRepo"
const OperationRepoServiceCallChain = "/codewiki.v1.RepoService/CallChain"
const OperationRepoServiceGetImplement = "/codewiki.v1.RepoService/GetImplement"
const OperationRepoServiceGetRepoTree = "/codewiki.v1.RepoService/GetRepoTree"
const OperationRepoServiceViewFileContent = "/codewiki.v1.RepoService/ViewFileContent"

type RepoServiceHTTPServer interface {
	// AnalyzeRepo Analyze by repository id
	AnalyzeRepo(context.Context, *AnalyzeRepoReq) (*AnalyzeResp, error)
	CallChain(context.Context, *CallChainReq) (*CallChainResp, error)
	// GetImplement interface  implement
	GetImplement(context.Context, *GetImplementReq) (*GetImplementResp, error)
	// GetRepoTree Repo tree display
	GetRepoTree(context.Context, *GetRepoTreeReq) (*GetRepoTreeResp, error)
	// ViewFileContent File  view  content
	ViewFileContent(context.Context, *ViewFileReq) (*ViewFileResp, error)
}

func RegisterRepoServiceHTTPServer(s *http.Server, srv RepoServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/api/functions/{id}/calls", _RepoService_CallChain0_HTTP_Handler(srv))
	r.POST("/v1/api/repos/{id}/analyze", _RepoService_AnalyzeRepo0_HTTP_Handler(srv))
	r.GET("/v1/api/repos/{id}/tree", _RepoService_GetRepoTree0_HTTP_Handler(srv))
	r.GET("/v1/api/{repoId}/file/{id}/view", _RepoService_ViewFileContent0_HTTP_Handler(srv))
	r.GET("/v1/api/entity/{id}/implements", _RepoService_GetImplement0_HTTP_Handler(srv))
}

func _RepoService_CallChain0_HTTP_Handler(srv RepoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CallChainReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRepoServiceCallChain)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CallChain(ctx, req.(*CallChainReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CallChainResp)
		return ctx.Result(200, reply)
	}
}

func _RepoService_AnalyzeRepo0_HTTP_Handler(srv RepoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AnalyzeRepoReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRepoServiceAnalyzeRepo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AnalyzeRepo(ctx, req.(*AnalyzeRepoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AnalyzeResp)
		return ctx.Result(200, reply)
	}
}

func _RepoService_GetRepoTree0_HTTP_Handler(srv RepoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRepoTreeReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRepoServiceGetRepoTree)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRepoTree(ctx, req.(*GetRepoTreeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRepoTreeResp)
		return ctx.Result(200, reply)
	}
}

func _RepoService_ViewFileContent0_HTTP_Handler(srv RepoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ViewFileReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRepoServiceViewFileContent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ViewFileContent(ctx, req.(*ViewFileReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ViewFileResp)
		return ctx.Result(200, reply)
	}
}

func _RepoService_GetImplement0_HTTP_Handler(srv RepoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetImplementReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRepoServiceGetImplement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetImplement(ctx, req.(*GetImplementReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetImplementResp)
		return ctx.Result(200, reply)
	}
}

type RepoServiceHTTPClient interface {
	AnalyzeRepo(ctx context.Context, req *AnalyzeRepoReq, opts ...http.CallOption) (rsp *AnalyzeResp, err error)
	CallChain(ctx context.Context, req *CallChainReq, opts ...http.CallOption) (rsp *CallChainResp, err error)
	GetImplement(ctx context.Context, req *GetImplementReq, opts ...http.CallOption) (rsp *GetImplementResp, err error)
	GetRepoTree(ctx context.Context, req *GetRepoTreeReq, opts ...http.CallOption) (rsp *GetRepoTreeResp, err error)
	ViewFileContent(ctx context.Context, req *ViewFileReq, opts ...http.CallOption) (rsp *ViewFileResp, err error)
}

type RepoServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRepoServiceHTTPClient(client *http.Client) RepoServiceHTTPClient {
	return &RepoServiceHTTPClientImpl{client}
}

func (c *RepoServiceHTTPClientImpl) AnalyzeRepo(ctx context.Context, in *AnalyzeRepoReq, opts ...http.CallOption) (*AnalyzeResp, error) {
	var out AnalyzeResp
	pattern := "/v1/api/repos/{id}/analyze"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRepoServiceAnalyzeRepo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RepoServiceHTTPClientImpl) CallChain(ctx context.Context, in *CallChainReq, opts ...http.CallOption) (*CallChainResp, error) {
	var out CallChainResp
	pattern := "/v1/api/functions/{id}/calls"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRepoServiceCallChain))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RepoServiceHTTPClientImpl) GetImplement(ctx context.Context, in *GetImplementReq, opts ...http.CallOption) (*GetImplementResp, error) {
	var out GetImplementResp
	pattern := "/v1/api/entity/{id}/implements"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRepoServiceGetImplement))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RepoServiceHTTPClientImpl) GetRepoTree(ctx context.Context, in *GetRepoTreeReq, opts ...http.CallOption) (*GetRepoTreeResp, error) {
	var out GetRepoTreeResp
	pattern := "/v1/api/repos/{id}/tree"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRepoServiceGetRepoTree))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RepoServiceHTTPClientImpl) ViewFileContent(ctx context.Context, in *ViewFileReq, opts ...http.CallOption) (*ViewFileResp, error) {
	var out ViewFileResp
	pattern := "/v1/api/{repoId}/file/{id}/view"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRepoServiceViewFileContent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationProjectServiceCreateProject = "/codewiki.v1.ProjectService/CreateProject"
const OperationProjectServiceDeleteProject = "/codewiki.v1.ProjectService/DeleteProject"
const OperationProjectServiceGetProject = "/codewiki.v1.ProjectService/GetProject"
const OperationProjectServiceListProjects = "/codewiki.v1.ProjectService/ListProjects"

type ProjectServiceHTTPServer interface {
	// CreateProject Repo management
	CreateProject(context.Context, *CreateProjectReq) (*CreateProjectResp, error)
	DeleteProject(context.Context, *DeleteProjectReq) (*DeleteProjectResp, error)
	GetProject(context.Context, *GetProjectReq) (*GetProjectResp, error)
	ListProjects(context.Context, *ListProjectReq) (*ListProjectResp, error)
}

func RegisterProjectServiceHTTPServer(s *http.Server, srv ProjectServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/api/project", _ProjectService_CreateProject0_HTTP_Handler(srv))
	r.GET("/v1/api/projects", _ProjectService_ListProjects0_HTTP_Handler(srv))
	r.GET("/v1/api/project/{id}", _ProjectService_GetProject0_HTTP_Handler(srv))
	r.DELETE("/v1/api/project/{id}", _ProjectService_DeleteProject0_HTTP_Handler(srv))
}

func _ProjectService_CreateProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProjectReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceCreateProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProject(ctx, req.(*CreateProjectReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProjectResp)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_ListProjects0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProjectReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceListProjects)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProjects(ctx, req.(*ListProjectReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProjectResp)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_GetProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProjectReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceGetProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProject(ctx, req.(*GetProjectReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProjectResp)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_DeleteProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProjectReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceDeleteProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProject(ctx, req.(*DeleteProjectReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteProjectResp)
		return ctx.Result(200, reply)
	}
}

type ProjectServiceHTTPClient interface {
	CreateProject(ctx context.Context, req *CreateProjectReq, opts ...http.CallOption) (rsp *CreateProjectResp, err error)
	DeleteProject(ctx context.Context, req *DeleteProjectReq, opts ...http.CallOption) (rsp *DeleteProjectResp, err error)
	GetProject(ctx context.Context, req *GetProjectReq, opts ...http.CallOption) (rsp *GetProjectResp, err error)
	ListProjects(ctx context.Context, req *ListProjectReq, opts ...http.CallOption) (rsp *ListProjectResp, err error)
}

type ProjectServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProjectServiceHTTPClient(client *http.Client) ProjectServiceHTTPClient {
	return &ProjectServiceHTTPClientImpl{client}
}

func (c *ProjectServiceHTTPClientImpl) CreateProject(ctx context.Context, in *CreateProjectReq, opts ...http.CallOption) (*CreateProjectResp, error) {
	var out CreateProjectResp
	pattern := "/v1/api/project"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProjectServiceCreateProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) DeleteProject(ctx context.Context, in *DeleteProjectReq, opts ...http.CallOption) (*DeleteProjectResp, error) {
	var out DeleteProjectResp
	pattern := "/v1/api/project/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProjectServiceDeleteProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) GetProject(ctx context.Context, in *GetProjectReq, opts ...http.CallOption) (*GetProjectResp, error) {
	var out GetProjectResp
	pattern := "/v1/api/project/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProjectServiceGetProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) ListProjects(ctx context.Context, in *ListProjectReq, opts ...http.CallOption) (*ListProjectResp, error) {
	var out ListProjectResp
	pattern := "/v1/api/projects"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProjectServiceListProjects))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
