// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: codewiki/v1/common.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_codewiki_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_codewiki_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_codewiki_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *BaseResp              `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_codewiki_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_codewiki_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_codewiki_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRet() *BaseResp {
	if x != nil {
		return x.Ret
	}
	return nil
}

var File_codewiki_v1_common_proto protoreflect.FileDescriptor

const file_codewiki_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18codewiki/v1/common.proto\x12\vcodewiki.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1copenapi/v3/annotations.proto\x1a\x17validate/validate.proto\"H\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"3\n" +
	"\bResponse\x12'\n" +
	"\x03ret\x18\x01 \x01(\v2\x15.codewiki.v1.BaseRespR\x03retB+\n" +
	"\n" +
	"codewikiV1P\x01Z\x1bcodewiki/api/codewiki/v1;v1b\x06proto3"

var (
	file_codewiki_v1_common_proto_rawDescOnce sync.Once
	file_codewiki_v1_common_proto_rawDescData []byte
)

func file_codewiki_v1_common_proto_rawDescGZIP() []byte {
	file_codewiki_v1_common_proto_rawDescOnce.Do(func() {
		file_codewiki_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codewiki_v1_common_proto_rawDesc), len(file_codewiki_v1_common_proto_rawDesc)))
	})
	return file_codewiki_v1_common_proto_rawDescData
}

var file_codewiki_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_codewiki_v1_common_proto_goTypes = []any{
	(*BaseResp)(nil), // 0: codewiki.v1.BaseResp
	(*Response)(nil), // 1: codewiki.v1.Response
}
var file_codewiki_v1_common_proto_depIdxs = []int32{
	0, // 0: codewiki.v1.Response.ret:type_name -> codewiki.v1.BaseResp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_codewiki_v1_common_proto_init() }
func file_codewiki_v1_common_proto_init() {
	if File_codewiki_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codewiki_v1_common_proto_rawDesc), len(file_codewiki_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codewiki_v1_common_proto_goTypes,
		DependencyIndexes: file_codewiki_v1_common_proto_depIdxs,
		MessageInfos:      file_codewiki_v1_common_proto_msgTypes,
	}.Build()
	File_codewiki_v1_common_proto = out.File
	file_codewiki_v1_common_proto_goTypes = nil
	file_codewiki_v1_common_proto_depIdxs = nil
}
