// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: codewiki/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason__                   ErrorReason = 0
	ErrorReason_ParamValidate       ErrorReason = 1
	ErrorReason_DataInsert          ErrorReason = 2
	ErrorReason_DataDelete          ErrorReason = 3
	ErrorReason_DataUpdate          ErrorReason = 4
	ErrorReason_DataQuery           ErrorReason = 5
	ErrorReason_DataRecordNotFound  ErrorReason = 6
	ErrorReason_Rpc                 ErrorReason = 7
	ErrorReason_BizDuplicateOp      ErrorReason = 8
	ErrorReason_NotFoundHostNetwork ErrorReason = 9
	ErrorReason_Acl                 ErrorReason = 10
	ErrorReason_ParseCodeError      ErrorReason = 1000
	ErrorReason_AnalyzeRelations    ErrorReason = 1001
	ErrorReason_AnalyzeDependencies ErrorReason = 1002
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:    "_",
		1:    "ParamValidate",
		2:    "DataInsert",
		3:    "DataDelete",
		4:    "DataUpdate",
		5:    "DataQuery",
		6:    "DataRecordNotFound",
		7:    "Rpc",
		8:    "BizDuplicateOp",
		9:    "NotFoundHostNetwork",
		10:   "Acl",
		1000: "ParseCodeError",
		1001: "AnalyzeRelations",
		1002: "AnalyzeDependencies",
	}
	ErrorReason_value = map[string]int32{
		"_":                   0,
		"ParamValidate":       1,
		"DataInsert":          2,
		"DataDelete":          3,
		"DataUpdate":          4,
		"DataQuery":           5,
		"DataRecordNotFound":  6,
		"Rpc":                 7,
		"BizDuplicateOp":      8,
		"NotFoundHostNetwork": 9,
		"Acl":                 10,
		"ParseCodeError":      1000,
		"AnalyzeRelations":    1001,
		"AnalyzeDependencies": 1002,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_codewiki_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_codewiki_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_codewiki_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_codewiki_v1_error_reason_proto protoreflect.FileDescriptor

const file_codewiki_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1ecodewiki/v1/error_reason.proto\x12\vcodewiki.v1\x1a\x13errors/errors.proto*\x8f\x02\n" +
	"\vErrorReason\x12\x05\n" +
	"\x01_\x10\x00\x12\x17\n" +
	"\rParamValidate\x10\x01\x1a\x04\xa8E\x90\x03\x12\x0e\n" +
	"\n" +
	"DataInsert\x10\x02\x12\x0e\n" +
	"\n" +
	"DataDelete\x10\x03\x12\x0e\n" +
	"\n" +
	"DataUpdate\x10\x04\x12\r\n" +
	"\tDataQuery\x10\x05\x12\x16\n" +
	"\x12DataRecordNotFound\x10\x06\x12\a\n" +
	"\x03Rpc\x10\a\x12\x12\n" +
	"\x0eBizDuplicateOp\x10\b\x12\x17\n" +
	"\x13NotFoundHostNetwork\x10\t\x12\a\n" +
	"\x03Acl\x10\n" +
	"\x12\x13\n" +
	"\x0eParseCodeError\x10\xe8\a\x12\x15\n" +
	"\x10AnalyzeRelations\x10\xe9\a\x12\x18\n" +
	"\x13AnalyzeDependencies\x10\xea\a\x1a\x04\xa0E\xf4\x03B9\n" +
	"\vcodewiki.v1P\x01Z\x1bcodewiki/api/codewiki/v1;v1\xa2\x02\n" +
	"codewikiV1b\x06proto3"

var (
	file_codewiki_v1_error_reason_proto_rawDescOnce sync.Once
	file_codewiki_v1_error_reason_proto_rawDescData []byte
)

func file_codewiki_v1_error_reason_proto_rawDescGZIP() []byte {
	file_codewiki_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_codewiki_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codewiki_v1_error_reason_proto_rawDesc), len(file_codewiki_v1_error_reason_proto_rawDesc)))
	})
	return file_codewiki_v1_error_reason_proto_rawDescData
}

var file_codewiki_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_codewiki_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: codewiki.v1.ErrorReason
}
var file_codewiki_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codewiki_v1_error_reason_proto_init() }
func file_codewiki_v1_error_reason_proto_init() {
	if File_codewiki_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codewiki_v1_error_reason_proto_rawDesc), len(file_codewiki_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codewiki_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_codewiki_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_codewiki_v1_error_reason_proto_enumTypes,
	}.Build()
	File_codewiki_v1_error_reason_proto = out.File
	file_codewiki_v1_error_reason_proto_goTypes = nil
	file_codewiki_v1_error_reason_proto_depIdxs = nil
}
