// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Neo4J         *Data_Neo4J            `protobuf:"bytes,1,opt,name=neo4j,proto3" json:"neo4j,omitempty"`
	PoolConfig    *PoolConfig            `protobuf:"bytes,2,opt,name=poolConfig,proto3" json:"poolConfig,omitempty"`
	Database      *Data_Database         `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Llm           *Data_LLM              `protobuf:"bytes,4,opt,name=llm,proto3" json:"llm,omitempty"`
	Embedding     *Data_Embedding        `protobuf:"bytes,5,opt,name=embedding,proto3" json:"embedding,omitempty"`
	Logger        *Zap                   `protobuf:"bytes,6,opt,name=logger,proto3" json:"logger,omitempty"`
	RepoDir       string                 `protobuf:"bytes,7,opt,name=repoDir,proto3" json:"repoDir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetNeo4J() *Data_Neo4J {
	if x != nil {
		return x.Neo4J
	}
	return nil
}

func (x *Data) GetPoolConfig() *PoolConfig {
	if x != nil {
		return x.PoolConfig
	}
	return nil
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetLlm() *Data_LLM {
	if x != nil {
		return x.Llm
	}
	return nil
}

func (x *Data) GetEmbedding() *Data_Embedding {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Data) GetLogger() *Zap {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *Data) GetRepoDir() string {
	if x != nil {
		return x.RepoDir
	}
	return ""
}

type PoolConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolSize      int32                  `protobuf:"varint,1,opt,name=poolSize,proto3" json:"poolSize,omitempty"`
	Blocking      bool                   `protobuf:"varint,2,opt,name=blocking,proto3" json:"blocking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolConfig) Reset() {
	*x = PoolConfig{}
	mi := &file_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolConfig) ProtoMessage() {}

func (x *PoolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolConfig.ProtoReflect.Descriptor instead.
func (*PoolConfig) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{3}
}

func (x *PoolConfig) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *PoolConfig) GetBlocking() bool {
	if x != nil {
		return x.Blocking
	}
	return false
}

type Zap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`                                //日志文件路径
	Console       bool                   `protobuf:"varint,2,opt,name=console,proto3" json:"console,omitempty"`                         //是否输出到终端，用于命令行启动显示
	MaxAge        int32                  `protobuf:"varint,3,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`             //最大存放天数，0为长期保存
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`                              //等级，默认info级别，有debug、info、warn、error等
	MaxSize       int32                  `protobuf:"varint,5,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`          //文件最大大小，M为单位
	MaxBackups    int32                  `protobuf:"varint,6,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"` //日志文件最大滚动数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zap) Reset() {
	*x = Zap{}
	mi := &file_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zap) ProtoMessage() {}

func (x *Zap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zap.ProtoReflect.Descriptor instead.
func (*Zap) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Zap) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Zap) GetConsole() bool {
	if x != nil {
		return x.Console
	}
	return false
}

func (x *Zap) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Zap) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Zap) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Zap) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Neo4J struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Neo4J) Reset() {
	*x = Data_Neo4J{}
	mi := &file_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Neo4J) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Neo4J) ProtoMessage() {}

func (x *Data_Neo4J) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Neo4J.ProtoReflect.Descriptor instead.
func (*Data_Neo4J) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Neo4J) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Data_Neo4J) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Neo4J) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Data_LLM struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BaseURL        string                 `protobuf:"bytes,1,opt,name=baseURL,proto3" json:"baseURL,omitempty"`
	ApiKey         string                 `protobuf:"bytes,2,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	EmbeddingModel string                 `protobuf:"bytes,3,opt,name=embeddingModel,proto3" json:"embeddingModel,omitempty"`
	LlmModelName   string                 `protobuf:"bytes,4,opt,name=llmModelName,proto3" json:"llmModelName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Data_LLM) Reset() {
	*x = Data_LLM{}
	mi := &file_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_LLM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_LLM) ProtoMessage() {}

func (x *Data_LLM) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_LLM.ProtoReflect.Descriptor instead.
func (*Data_LLM) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_LLM) GetBaseURL() string {
	if x != nil {
		return x.BaseURL
	}
	return ""
}

func (x *Data_LLM) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Data_LLM) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *Data_LLM) GetLlmModelName() string {
	if x != nil {
		return x.LlmModelName
	}
	return ""
}

type Data_Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiURL        string                 `protobuf:"bytes,1,opt,name=apiURL,proto3" json:"apiURL,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	ModelName     string                 `protobuf:"bytes,3,opt,name=modelName,proto3" json:"modelName,omitempty"`
	Dimension     int32                  `protobuf:"varint,4,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Embedding) Reset() {
	*x = Data_Embedding{}
	mi := &file_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Embedding) ProtoMessage() {}

func (x *Data_Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Embedding.ProtoReflect.Descriptor instead.
func (*Data_Embedding) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Data_Embedding) GetApiURL() string {
	if x != nil {
		return x.ApiURL
	}
	return ""
}

func (x *Data_Embedding) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Data_Embedding) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *Data_Embedding) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

var File_conf_proto protoreflect.FileDescriptor

const file_conf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"]\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xdc\x05\n" +
	"\x04Data\x12,\n" +
	"\x05neo4j\x18\x01 \x01(\v2\x16.kratos.api.Data.Neo4jR\x05neo4j\x126\n" +
	"\n" +
	"poolConfig\x18\x02 \x01(\v2\x16.kratos.api.PoolConfigR\n" +
	"poolConfig\x125\n" +
	"\bdatabase\x18\x03 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12&\n" +
	"\x03llm\x18\x04 \x01(\v2\x14.kratos.api.Data.LLMR\x03llm\x128\n" +
	"\tembedding\x18\x05 \x01(\v2\x1a.kratos.api.Data.EmbeddingR\tembedding\x12'\n" +
	"\x06logger\x18\x06 \x01(\v2\x0f.kratos.api.ZapR\x06logger\x12\x18\n" +
	"\arepoDir\x18\a \x01(\tR\arepoDir\x1aW\n" +
	"\x05Neo4j\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x1a:\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x1a\x83\x01\n" +
	"\x03LLM\x12\x18\n" +
	"\abaseURL\x18\x01 \x01(\tR\abaseURL\x12\x16\n" +
	"\x06apiKey\x18\x02 \x01(\tR\x06apiKey\x12&\n" +
	"\x0eembeddingModel\x18\x03 \x01(\tR\x0eembeddingModel\x12\"\n" +
	"\fllmModelName\x18\x04 \x01(\tR\fllmModelName\x1aw\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06apiURL\x18\x01 \x01(\tR\x06apiURL\x12\x16\n" +
	"\x06apiKey\x18\x02 \x01(\tR\x06apiKey\x12\x1c\n" +
	"\tmodelName\x18\x03 \x01(\tR\tmodelName\x12\x1c\n" +
	"\tdimension\x18\x04 \x01(\x05R\tdimension\"D\n" +
	"\n" +
	"PoolConfig\x12\x1a\n" +
	"\bpoolSize\x18\x01 \x01(\x05R\bpoolSize\x12\x1a\n" +
	"\bblocking\x18\x02 \x01(\bR\bblocking\"\x9e\x01\n" +
	"\x03Zap\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x18\n" +
	"\aconsole\x18\x02 \x01(\bR\aconsole\x12\x17\n" +
	"\amax_age\x18\x03 \x01(\x05R\x06maxAge\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x19\n" +
	"\bmax_size\x18\x05 \x01(\x05R\amaxSize\x12\x1f\n" +
	"\vmax_backups\x18\x06 \x01(\x05R\n" +
	"maxBackupsB\x1dZ\x1bcodewiki/internal/conf;confb\x06proto3"

var (
	file_conf_proto_rawDescOnce sync.Once
	file_conf_proto_rawDescData []byte
)

func file_conf_proto_rawDescGZIP() []byte {
	file_conf_proto_rawDescOnce.Do(func() {
		file_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)))
	})
	return file_conf_proto_rawDescData
}

var file_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*PoolConfig)(nil),          // 3: kratos.api.PoolConfig
	(*Zap)(nil),                 // 4: kratos.api.Zap
	(*Server_HTTP)(nil),         // 5: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 6: kratos.api.Server.GRPC
	(*Data_Neo4J)(nil),          // 7: kratos.api.Data.Neo4j
	(*Data_Database)(nil),       // 8: kratos.api.Data.Database
	(*Data_LLM)(nil),            // 9: kratos.api.Data.LLM
	(*Data_Embedding)(nil),      // 10: kratos.api.Data.Embedding
	(*durationpb.Duration)(nil), // 11: google.protobuf.Duration
}
var file_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	5,  // 2: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	6,  // 3: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	7,  // 4: kratos.api.Data.neo4j:type_name -> kratos.api.Data.Neo4j
	3,  // 5: kratos.api.Data.poolConfig:type_name -> kratos.api.PoolConfig
	8,  // 6: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	9,  // 7: kratos.api.Data.llm:type_name -> kratos.api.Data.LLM
	10, // 8: kratos.api.Data.embedding:type_name -> kratos.api.Data.Embedding
	4,  // 9: kratos.api.Data.logger:type_name -> kratos.api.Zap
	11, // 10: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	11, // 11: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_conf_proto_init() }
func file_conf_proto_init() {
	if File_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_proto_goTypes,
		DependencyIndexes: file_conf_proto_depIdxs,
		MessageInfos:      file_conf_proto_msgTypes,
	}.Build()
	File_conf_proto = out.File
	file_conf_proto_goTypes = nil
	file_conf_proto_depIdxs = nil
}
